# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fcd53110a66f48e562406292da44fbf6951514b99da7effcb3aa2d3a57310e347a9de64b7a033b8acbd139159134eb70737a175619f848e9797496433ffe3739

test:
  secret_key_base: ff671a8ab09e01640b27076f87a805cd2be21bdadc3e6c9725d7c64c69c737953d06106d6ec0001aa0313c8b57839c443524d4b812b8ed60ef3811d3dcdbe867

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
